[windows]

dc01 ansible_host=10.10.1.4

app01 ansible_host=10.10.1.5


[windows:vars]

ansible_user=labadmin

ansible_password=xe#45dng

ansible_connection=winrm

ansible_winrm_transport=ntlm

ansible_port=5985

ansible_winrm_server_cert_validation=ignore
